services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - appnet

networks:
  appnet:
